{
 "title": "Itau AutoInvest - Overview",
 "tags": [
  "observabilidade",
  "dotnet"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Métricas de Sistema", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(dotnet_process_cpu_time_seconds_total[1m])) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Uso de Memória",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "dotnet_process_memory_working_set_bytes",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  { "title": "Telemetria de API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Throughput (Req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count[1m]))",
     "legendFormat": "Requisições por Segundo"
    }
   ]
  },
  {
   "title": "Latência Média de API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(http_server_request_duration_seconds_sum / http_server_request_duration_seconds_count)",
     "legendFormat": "Latência Média"
    }
   ]
  },
  {
   "title": "Erros no Última Hora (Logs)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"itau-autoinvest-api\"} | json | detected_level=\"error\" [1h]))"
    }
   ]
  },
  { "title": "Banco de Dados e EF Core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "MySQL - Conexões Ativas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected",
     "legendFormat": "Conexões Ativas"
    }
   ]
  },
  {
   "title": "EF Core - Queries por Segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(microsoft_entityframeworkcore_queries_total[1m]))",
     "legendFormat": "Queries por Segundo (EF Core)"
    }
   ]
  },
  { "title": "Logs Estruturados", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Visualização de Logs (Loki)",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"itau-autoinvest-api\"}"
    }
   ]
  }
 ]
}