// <auto-generated />
using System;
using Itau.AutoInvest.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Itau.AutoInvest.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260227142647_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Itau.AutoInvest.Infrastructure.Tables.BasketItemsTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ParentBasketId")
                        .HasColumnType("bigint")
                        .HasColumnName("CestaId");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("Percentual");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ParentBasketId");

                    b.ToTable("ItensCesta");
                });

            modelBuilder.Entity("Itau.AutoInvest.Infrastructure.Tables.BasketRecommendationTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataCriacao");

                    b.Property<DateTime>("DeactivationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataDesativacao");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Ativa");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("CestasRecomendacao");
                });

            modelBuilder.Entity("Itau.AutoInvest.Infrastructure.Tables.BuyOrderTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GraphicalAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("ContaMasterId");

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasColumnType("ENUM('LOTE','FRACIONARIO')")
                        .HasColumnName("TipoMercado");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantidade");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("PrecoUnitario");

                    b.HasKey("Id");

                    b.HasIndex("GraphicalAccountId");

                    b.ToTable("OrdensCompra");
                });

            modelBuilder.Entity("Itau.AutoInvest.Infrastructure.Tables.ClientsTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AccessDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataAcesso");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("CPF");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("Ativo");

                    b.Property<decimal>("MonthlyValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("ValorMensal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Itau.AutoInvest.Infrastructure.Tables.CurrenciesTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ClosingPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("PrecoFechamento");

                    b.Property<decimal>("MaximumPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("PrecoMaximo");

                    b.Property<decimal>("MinimumPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("PrecoMinimo");

                    b.Property<decimal>("OpeningPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("PrecoAbertura");

                    b.Property<DateTime>("PreachDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataPregao");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Cotacoes");
                });

            modelBuilder.Entity("Itau.AutoInvest.Infrastructure.Tables.CustodiesTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AvaragePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecoMedio");

                    b.Property<long>("GraphicalAccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("ContaGraficaId");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataUltimaAtualizacao");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantidade");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("GraphicalAccountId");

                    b.ToTable("Custodias");
                });

            modelBuilder.Entity("Itau.AutoInvest.Infrastructure.Tables.DistributionsTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BuyOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("OrdemCompraId");

                    b.Property<long>("CustodyId")
                        .HasColumnType("bigint")
                        .HasColumnName("CustodiaFilhoteId");

                    b.Property<DateTime>("DistributionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataDistribuicao");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantidade");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("PrecoUnitario");

                    b.HasKey("Id");

                    b.HasIndex("BuyOrderId");

                    b.HasIndex("CustodyId");

                    b.ToTable("Distribuicoes");
                });

            modelBuilder.Entity("Itau.AutoInvest.Infrastructure.Tables.GraphicalAccountsTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("NumeroConta");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("ENUM('MASTER', 'FILHOTE')")
                        .HasColumnName("Tipo");

                    b.Property<long>("ClientId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("ClienteId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataCriacao");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("ContasGraficas");
                });

            modelBuilder.Entity("Itau.AutoInvest.Infrastructure.Tables.IREventsTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BaseValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorBase");

                    b.Property<long>("ClientId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("ClienteId");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataEvento");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("ENUM('DEDO_DURO','IR_VENDA')")
                        .HasColumnName("Tipo");

                    b.Property<decimal>("IRValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorIR");

                    b.Property<bool>("IsPublishedOnKafka")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("PublicadoKafka");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("EventosIR");
                });

            modelBuilder.Entity("Itau.AutoInvest.Infrastructure.Tables.RebalancesTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("ClienteId");

                    b.Property<DateTime>("DateRebalancing")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DataRebalanceamento");

                    b.Property<string>("RebalanceType")
                        .IsRequired()
                        .HasColumnType("ENUM('MUNDANCA_CESTA', 'DESVIO')")
                        .HasColumnName("Tipo");

                    b.Property<decimal>("SalesValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorVenda");

                    b.Property<string>("TickerPurchased")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("TickerComprado");

                    b.Property<string>("TickerSold")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("TickerVendido");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Rebalanceamentos");
                });

            modelBuilder.Entity("Itau.AutoInvest.Infrastructure.Tables.BasketItemsTable", b =>
                {
                    b.HasOne("Itau.AutoInvest.Infrastructure.Tables.BasketRecommendationTable", "ParentBasket")
                        .WithMany()
                        .HasForeignKey("ParentBasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentBasket");
                });

            modelBuilder.Entity("Itau.AutoInvest.Infrastructure.Tables.BuyOrderTable", b =>
                {
                    b.HasOne("Itau.AutoInvest.Infrastructure.Tables.GraphicalAccountsTable", "GraphicalAccount")
                        .WithMany()
                        .HasForeignKey("GraphicalAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GraphicalAccount");
                });

            modelBuilder.Entity("Itau.AutoInvest.Infrastructure.Tables.CustodiesTable", b =>
                {
                    b.HasOne("Itau.AutoInvest.Infrastructure.Tables.GraphicalAccountsTable", "GraphicalAccount")
                        .WithMany()
                        .HasForeignKey("GraphicalAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GraphicalAccount");
                });

            modelBuilder.Entity("Itau.AutoInvest.Infrastructure.Tables.DistributionsTable", b =>
                {
                    b.HasOne("Itau.AutoInvest.Infrastructure.Tables.BuyOrderTable", "BuyOrder")
                        .WithMany()
                        .HasForeignKey("BuyOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Itau.AutoInvest.Infrastructure.Tables.CustodiesTable", "Custody")
                        .WithMany()
                        .HasForeignKey("CustodyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuyOrder");

                    b.Navigation("Custody");
                });

            modelBuilder.Entity("Itau.AutoInvest.Infrastructure.Tables.GraphicalAccountsTable", b =>
                {
                    b.HasOne("Itau.AutoInvest.Infrastructure.Tables.ClientsTable", "Client")
                        .WithOne("GraphicalAccountTable")
                        .HasForeignKey("Itau.AutoInvest.Infrastructure.Tables.GraphicalAccountsTable", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Itau.AutoInvest.Infrastructure.Tables.IREventsTable", b =>
                {
                    b.HasOne("Itau.AutoInvest.Infrastructure.Tables.ClientsTable", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Itau.AutoInvest.Infrastructure.Tables.RebalancesTable", b =>
                {
                    b.HasOne("Itau.AutoInvest.Infrastructure.Tables.ClientsTable", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Itau.AutoInvest.Infrastructure.Tables.ClientsTable", b =>
                {
                    b.Navigation("GraphicalAccountTable")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
