{
 "title": "Itau AutoInvest - Overview",
 "tags": [
  "observabilidade",
  "dotnet"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Métricas de Sistema", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "CPU Usage" }
   ]
  },
  {
   "title": "Uso de Memória",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_private_memory_bytes", "legendFormat": "Memory Usage" }
   ]
  },
  { "title": "Telemetria de API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Throughput (Req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count[1m]))",
     "legendFormat": "Requisições por Segundo"
    }
   ]
  },
  {
   "title": "Latência Média de API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(http_server_request_duration_seconds_sum / http_server_request_duration_seconds_count)",
     "legendFormat": "Latência Média"
    }
   ]
  },
  {
   "title": "Erros no Último Minuto (Logs)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({Level='Error'} [1m])"
    }
   ]
  },
  { "title": "Logs Estruturados", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Visualização de Logs (Loki)",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "targets": [
    { "expr": "{job='itau-autoinvest-api'}" }
   ]
  }
 ]
}